-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS BANCO_TESOURO_AZUL;
USE BANCO_TESOURO_AZUL;

-- Tabela TB_TIPO_ASSINATURA
CREATE TABLE TB_TIPO_ASSINATURA (
    ID_TIPO INT AUTO_INCREMENT PRIMARY KEY,
    DESC_TIPO VARCHAR(20) NOT NULL UNIQUE
);

-- Tabela TB_ASSINATURA
CREATE TABLE TB_ASSINATURA (
    ID_ASSINATURA INT AUTO_INCREMENT PRIMARY KEY,
    DESC_ASSINATURA VARCHAR(50) NOT NULL UNIQUE,
    VALOR_ASSINATURA DECIMAL(5,2) NOT NULL UNIQUE,
    TIPO_ASSINATURA_FK INT NOT NULL,
    FOREIGN KEY (TIPO_ASSINATURA_FK) REFERENCES TB_TIPO_ASSINATURA(ID_TIPO)
);

-- Tabela TB_USUARIO
CREATE TABLE TB_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_USUARIO VARCHAR(80) NOT NULL UNIQUE,
    EMAIL_USUARIO VARCHAR(100) NOT NULL UNIQUE,
    DATA_NASC_USUARIO DATE NOT NULL,
    CPF_USUARIO CHAR(11) NOT NULL UNIQUE,
    CNPJ_USUARIO CHAR(14) NULL,
    PLANO_USUARIO_FK INT NOT NULL,
    SENHA_USUARIO VARCHAR(255) NOT NULL,
    FOTO_USUARIO TEXT NULL,
    FOREIGN KEY (PLANO_USUARIO_FK) REFERENCES TB_ASSINATURA(ID_ASSINATURA)
);

CREATE TABLE TB_CADASTRO_ADMINISTRADOR(
	ID_USUARIO_ADM INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ADMINISTRADOR VARCHAR(40)NOT NULL,
    EMAIL_ADMINISTRADOR VARCHAR (100) NOT NULL UNIQUE,
    SENHA_ADMINISTRADOR VARCHAR(255) NOT NULL
    

    );

-- Tabela TB_PRODUTO
CREATE TABLE TB_PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    COD_PRODUTO VARCHAR(80) NOT NULL UNIQUE,
    NOME_PRODUTO VARCHAR(100) NOT NULL UNIQUE,
    TIPO_PRODUTO VARCHAR(40) NOT NULL,
    DATA_VALIDADE DATE NULL,
    IMG_PRODUTO TEXT NULL
);

-- Tabela TB_FORNECEDOR
CREATE TABLE TB_FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(40) NOT NULL UNIQUE,
    CNPJ_FORNECEDOR CHAR(14) NOT NULL UNIQUE,
    EMAIL_FORNECEDOR VARCHAR(35) NOT NULL,
    TEL_FORNECEDOR CHAR(14) NULL UNIQUE,
    CEL_FORNECEDOR CHAR(15) NOT NULL UNIQUE,
    ENDERECO_FORNECEDOR VARCHAR(50) NOT NULL
);

-- Tabela TB_PEDIDO_COMPRA
CREATE TABLE TB_PEDIDO_COMPRA (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    NUM_PEDIDO VARCHAR(14) NOT NULL UNIQUE,
    CNPJ_FORNECEDOR_FK CHAR NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    QUANTIDADE_PEDIDO DECIMAL(5,2) NOT NULL,
    COD_LOTE_PEDIDO VARCHAR(13) NOT NULL UNIQUE,
    NOME_PRODUTO_PEDIDO VARCHAR(50) NOT NULL,
    VALOR_PEDIDO DECIMAL(5,2) NOT NULL,
    FOREIGN KEY(CNPJ_FORNECEDOR_FK) REFERENCES TB_FORNECEDOR(CNPJ_FORNECEDOR)
);


-- Tabela TB_PEDIDO_VENDA
CREATE TABLE TB_PEDIDO_VENDA (
    ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO_FK INT NOT NULL,
    COD_LOTE_VENDA VARCHAR(20) NOT NULL,
    DATA_VENDA DATE NOT NULL,
    VALOR_TOTAL DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO_FK) REFERENCES TB_PEDIDO_COMPRA(ID_PEDIDO)
);

-- Tabela TB_ITEM_COMPRA
CREATE TABLE TB_ITEM_COMPRA (
    ID_ITEM_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO_FK INT NOT NULL,
    ID_PRODUTO_FK INT NOT NULL,
    NOME_PRODUTO_FK VARCHAR(100) NOT NULL COMMENT 'Cópia do nome no momento da compra',
    QUANTIDADE DECIMAL(10,2) NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    COD_LOTE VARCHAR(20) NULL,
    FOREIGN KEY (ID_PEDIDO_FK) REFERENCES TB_PEDIDO_COMPRA(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO_FK) REFERENCES TB_PRODUTO(ID_PRODUTO),
    FOREIGN KEY (NOME_PRODUTO_FK) REFERENCES TB_PRODUTO(NOME_PRODUTO)
);

-- Tabela TB_ITEM_VENDA (nova tabela sugerida)
CREATE TABLE TB_ITEM_VENDA (
    ID_ITEM_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA_FK INT NOT NULL,
    ID_PRODUTO_FK INT NOT NULL,
    NOME_PRODUTO_FK VARCHAR(100) NOT NULL COMMENT 'Cópia do nome no momento da venda',
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_VENDA_FK) REFERENCES TB_PEDIDO_VENDA(ID_VENDA),
    FOREIGN KEY (ID_PRODUTO_FK) REFERENCES TB_PRODUTO(ID_PRODUTO),
    FOREIGN KEY (NOME_PRODUTO_FK) REFERENCES TB_PRODUTO(NOME_PRODUTO)
);

-- Adicionando constraints adicionais
ALTER TABLE TB_USUARIO 
ADD CONSTRAINT CK_SENHA_USUARIO 
CHECK (LENGTH(SENHA_USUARIO) BETWEEN 8 AND 20);

ALTER TABLE TB_PEDIDO_COMPRA
ADD CONSTRAINT UK_PEDIDO_FORNECEDOR 
UNIQUE (NUM_PEDIDO, CNPJ_FORNECEDOR_FK);

-- Criando índices para melhorar performance
